# name: Get Citation Data

# on: 
#  page_build: 
#  schedule:
#   - cron:  '0 8 * * *'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       # Reference the major version of a release
#     - uses: actions/checkout@v4
#     - name: Setup Node
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'
#     - name: Install Reqs
#       run: |
#         sudo apt-get install python3-setuptools
#     - name: Run
#       run: |
#         cd ./google_scholar_crawler
#         pip3 install -r requirements.txt
#         python3 main.py
#         cd ./results
#         git init
#         git config --local user.name "${GITHUB_ACTOR}"
#         export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
#         git add *.json
#         git commit -m "Updated Citation Data"
#         git push "${remote_repo}" HEAD:google-scholar-stats --force
#       env: 
#         GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}



# update 250802

name: Update Google Scholar Citations

on:
  schedule:
    - cron: '0 0 * * *' # 每天 0 点执行
  workflow_dispatch: # 支持手动触发

jobs:
  update-citations:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install scholarly

      - name: Update citation data
        run: python update_gs_data.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add google-scholar-stats/gs_data_shieldsio.json
          git commit -m "Update Google Scholar citations" || echo "No changes"
          git push