name: Update Google Scholar Citations

on:
  schedule:
    - cron: '0 0 * * *' # 每天 0 点执行
  workflow_dispatch: # 支持手动触发

jobs:
  update-citations:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install scholarly

      - name: Update citation data
        run: python update_gs_data.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add google-scholar-stats/gs_data_shieldsio.json
          git commit -m "Update Google Scholar citations" || echo "No changes"
          git push